### ISSUE TITLE
Zookeeper not using ZOO_SERVER_ID variable

### ISSUE THREAD

**Issue by akumadare** [bitnami/bitnami-docker-zookeeper#11]
**Description**

Zookeeper stops on startup when using a persistent volume and configuring thru environment variables.

**Steps to reproduce the issue:**

1. Start the container
```
docker run -it --rm -e ZOO_SERVER_ID=1 -e ALLOW_ANONYMOUS_LOGIN=yes \
-e ZOO_SERVERS=server1:2888:3888,server2:2888:3888 \
-v /tmp:/bitnami/zookeeper/data \
bitnami/zookeeper
```

**Describe the results you received:**

Container starts but zookeeper goes into error
```
2019-01-28 11:43:09,628 [myid:] - ERROR [main:QuorumPeerMain@88] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:156)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:104)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:81)
Caused by: java.lang.IllegalArgumentException: /opt/bitnami/zookeeper/data/myid file is missing
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:408)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:152)
        ... 2 more
Invalid config, exiting abnormally
```

**Describe the results you expected:**

I expected zookeeper to start and use the the id set in ZOO_SERVER_ID

**Additional information you deem important (e.g. issue happens only occasionally):**

I created a myid (containing '1') file under /tmp/ and restarted the container, zookeeper starts with no issues. This should not be required as the env variable should be used.

**Version**

- Output of `docker version`:

```
lient:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Oct 26 23:38:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Oct 26 23:39:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 12
 Running: 5
 Paused: 0
 Stopped: 7
Images: 8
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 1.504GB
 Data Space Total: 23.33GB
 Data Space Available: 21.83GB
 Metadata Space Used: 3.957MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 21.21MB
 Thin Pool Minimum Free Space: 2.333GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.77-69.57.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ip-10-0-20-130
ID: NSKP:KZ4F:6NOP:NS7D:L2TB:EDZG:RKCI:BVIK:EP2I:7AGF:RGOS:M4Y2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Could you show the error that appears? We want to to discard it is a permission issue

**Comment by akumadare** [comment]
Hi. My original post was supposed to have the error details but i posted the wrong content into the second code box - i have updated this now.
I have also updated the permissions on the /tmp folder to 777 which I have used as the volume in my example - this also fails with the same error.

**Comment by javsalgar** [comment]
Hi,

I was not able to reproduce it. I tried with this docker-compose file

```
version: '2'

services:
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    volumes:
      - /path/to/zookeeper-persistence:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper2:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    volumes:
      - /path/to/zookeeper-persistence:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
  zookeeper3:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    volumes:
      - /path/to/zookeeper-persistence:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
```

Could you check if this one works for you?
