### ISSUE TITLE
Error executing 'postInstallation': EROFS: read-only file system

### ISSUE THREAD

**Issue by justpolidor** [bitnami/bitnami-docker-zookeeper#12]
**Description**

Zookeeper (and bitnami/kafka) CrashLoopBackOff: Error executing 'postInstallation': EROFS: read-only file system, utime '/bitnami/zookeeper/.restored'.
There are 5 Zookeeper deployed on Oracle Kubernetes Environment (Oracle Cloud) and 2 of them crashed (note that the cluster is in idle... kafka isn't receiving any messages). 

**Steps to reproduce the issue:**

1. Deploy a zookeeper cluster as follow:

```
Source:` zookeeper/templates/statefulset.yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: "zookeeper"
  namespace: prod-red
  labels:
    app: zookeeper
spec:
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data-prod
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "30Gi"
  serviceName: zookeeper-headless
  replicas: 5
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - zookeeper
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - zookeeper
                topologyKey: "failure-domain.beta.kubernetes.io/zone"
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: "zookeeper"
          image: "repository/zookeeper-bitnami:3.4.13"
          imagePullPolicy: "Always"
          command:
            - bash
            - -ec
            - |
              # Execute entrypoint as usual after obtaining ZOO_SERVER_ID based on POD hostname
              HOSTNAME=`hostname -s`
              if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
                ORD=${BASH_REMATCH[2]}
                export ZOO_SERVER_ID=$((ORD+1))
              else
                echo "Failed to get index from hostname $HOST"
                exit 1
              fi
              . /opt/bitnami/base/functions
              . /opt/bitnami/base/helpers
              print_welcome_page
              . /init.sh
              nami_initialize zookeeper
              exec tini -- /run.sh
          resources:
            requests:
              cpu: 250m
              memory: 2048Mi
          env:
            - name: ZOO_PORT_NUMBER
              value: "2181"
            - name: ZOO_TICK_TIME
              value: "2000"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "5"
            - name: ZOO_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOO_SERVERS
              value: "zookeeper-0.zookeeper-headless.prod-red.svc.cluster.local:2888:3888,zookeeper-1.zookeeper-headless.prod-red.svc.cluster.local:2888:3888,zookeeper-2.zookeeper-headless.prod-red.svc.cluster.local:2888:3888,zookeeper-3.zookeeper-headless.prod-red.svc.cluster.local:2888:3888,zookeeper-4.zookeeper-headless.prod-red.svc.cluster.local:2888:3888"
            - name: ZOO_HEAP_SIZE
              value: "1024"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: election
              containerPort: 3888
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: zookeeper-data-prod
              mountPath: /bitnami/zookeeper
      imagePullSecrets:
        - name: regcred
```
2. Wait the crash

**Describe the results you received:**

Error executing 'postInstallation': EROFS: read-only file system, utime '/bitnami/zookeeper/.restored'.

I tried to manually delete a failed zookeeper but it is stuck in ContainerCreating:
Warning  FailedMount  92s (x16 over 35m)  kubelet, 10.29.2.11  Unable to mount volumes for pod "zookeeper-1_prod-red(93bda653-8810-11e9-910e-0a580aed3e12)": timeout expired waiting for volumes to attach or mount for pod "prod-red"/"zookeeper-1". list of unmounted volumes=[zookeeper-data-prod]. list of unattached volumes=[zookeeper-data-prod default-token-mtf6p] 

I don't have access to docker engine as Kubernetes is as a Service. 

This is the situation: 

```
kafka-0                                 1/1     Running             6          2d    10.95.1.62    10.29.129.13   <none>
kafka-1                                 0/1     CrashLoopBackOff    91         2d    10.95.4.41    10.29.130.12   <none>
kafka-2                                 1/1     Running             6          2d    10.95.3.42    10.29.131.10   <none>
kafka-3                                 1/1     Running             6          2d    10.95.11.33   10.29.129.14   <none>
kafka-4                                 0/1     Error               85         2d    10.95.5.32    10.29.130.11   <none>
zookeeper-0                         1/1     Running             0          2d    10.95.11.34   10.29.129.14   <none>
zookeeper-1                         0/1     ContainerCreating   0          52m   <none>        10.29.130.11   <none>
zookeeper-2                         1/1     Running             0          2d    10.95.3.43    10.29.131.10   <none>
zookeeper-3                         1/1     Running             1          2d    10.95.1.63    10.29.129.13   <none>
zookeeper-4                         0/1     CrashLoopBackOff    89         2d    10.95.4.42    10.29.130.12   <none>

```

**Comment by miguelaeh** [comment]
Hi @justpolidor ,
Have you try to use an init container to set the volume permissions?
Also, please, could you paste the code correctly indented?

**Comment by justpolidor** [comment]
Hi @miguelaeh , sorry for the indent. 

Yes, I tried right now. It is stuck on PodInitializing status. 
If I do a describe it says the same:
`Warning  FailedMount  65s (x2 over 3m20s)  kubelet, 10.29.130.12  Unable to mount volumes for pod "zookeeper-4_prod-red(2f908923-8835-11e9-910e-0a580aed3e12)": timeout expired waiting for volumes to attach or mount for pod "prod-red"/"zookeeper-4". list of unmounted volumes=[zookeeper-data-prod]. list of unattached volumes=[zookeeper-data-prod default-token-mtf6p]`

I have added this section to my deploy file:

```
spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R g+rwX /bitnami/zookeeper']
          volumeMounts:
            - mountPath: /bitnami/zookeeper
              name: zookeeper-data-prod
```
