### ISSUE TITLE
ZOO_ENABLE_AUTH=yes has no effect

### ISSUE THREAD

**Issue by cwienands1** [bitnami/bitnami-docker-zookeeper#13]
I am trying to enable SASL authentication without SSL for the communication between Zookeeper nodes themselves and also Kafka to Zookeeper. I am using docker-compose to start up a single-node ensemble at this time.

How to reproduce:
1. I have followed the instructions on the readme under https://github.com/bitnami/bitnami-docker-zookeeper#security and configured those 5 env vars accordingly.
2. For the Kafka nodes I have configured the env vars KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD.
3. I order to verify that authentication is working correctly, I **misconfigured** the password used by the Kafka nodes, with the expectation that they will **not** be able to connect to Zookeeper.

Result: All nodes (Kafka and Zookeeper) start up without any issue. I can also use the zookeeper-shell tool to connect to Zookeeper without any authentication.

Expected: Kafka nodes should report errors from connection attempts to Zookeeper nodes, along the lines that they cannot authenticate.

More info:
I started investigating the content of the Zookeeper image (only *env* and zookeeper-inputs.json so far). That file and the env vars looked OK to me, the settings from the docker-compose file were present. I am still looking for information on where on disk all those Zookeeper config files are, to compare them to recommended settings for SASL authentication (which I don't know yet, either).

Version: Docker tag bitnami/zookeeper:3, pulled around 7/18/2019. Sorry, I don't know where to find the exact version of the image or Zookeeper itself.

Docker version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Docker info:
Containers: 22
 Running: 3
 Paused: 0
 Stopped: 19
Images: 13
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.077GiB
Name: linuxkit-00155d656904
ID: EF2A:4N2L:QHZ7:H3QQ:LCI7:NKMW:U7RP:6EGO:F4LY:MFIJ:5AFT:RHL2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 72
 System Time: 2019-07-25T14:59:26.6506638Z
 EventsListeners: 2
HTTP Proxy: 192.168.100.1:3128
HTTPS Proxy: 192.168.100.1:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker.jfrog.lfg.com/
Live Restore Enabled: false
Product License: Community Engine

Docker-compose version:
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

Environment:
Host: Physical machine with Windows 10 with Docker for Windows

**Comment by miguelaeh** [comment]
Hi @cwienands1 ,
It can be possible that you deploy the `docker-compose` before and now the passwords are stored on the volumes. Try to execute `docker-compose down -v` to remove the volumes and try again without passwords.

**Comment by cwienands1** [comment]
@miguelaeh I had already tried that yesterday but just to be sure repeated today. I verified that the volumes were removed after the down before restarting. Still, same behavior, authentication is not enabled. For what it's worth, here are the ZK outputs from the first run (which crashed after a few mins) and a subsequent run:

First run, exited after a few mins...
```
zookeeper_1  |
zookeeper_1  | Welcome to the Bitnami zookeeper container
zookeeper_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
zookeeper_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
zookeeper_1  |
zookeeper_1  | nami    INFO  Initializing zookeeper
zookeeper_1  | zookeep INFO  ==> No injected configuration files found. Creating default config file...
zookeeper_1  | zookeep INFO  ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
zookeeper_1  | zookeep INFO  ==> Enabling authentication...
zookeeper_1  | zookeep INFO  ==> Creating jaas file
zookeeper_1  | zookeep INFO  ==> Deploying ZooKeeper from scratch...
zookeeper_1  | zookeep INFO  ==> Validating inputs...
zookeeper_1  | zookeep INFO  ==> Setting the ACL rule "sasl:kafka:crdwa" in /
zookeeper_1  | Error executing 'postInstallation': Could not set ACL rules
bitnami-docker-kafka_zookeeper_1 exited with code 1
```

Second run...
```
zookeeper_1  |
zookeeper_1  | Welcome to the Bitnami zookeeper container
zookeeper_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
zookeeper_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
zookeeper_1  |
zookeeper_1  | nami    INFO  Initializing zookeeper
zookeeper_1  | zookeep INFO  ==> Configuration files found...
zookeeper_1  | zookeep INFO  ==> Deploying ZooKeeper with persisted data...
zookeeper_1  | nami    INFO  zookeeper successfully initialized
zookeeper_1  | INFO  ==> Starting zookeeper...
zookeeper_1  | /opt/bitnami/java/bin/java
zookeeper_1  | ZooKeeper JMX enabled by default
zookeeper_1  | Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
zookeeper_1  | Starting zookeeper ... STARTED
zookeeper_1  | 2019-07-26 15:00:13,640 [myid:1] - INFO  [main:ServerCnxnFactory@135] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
zookeeper_1  | 2019-07-26 15:00:13,647 [myid:1] - INFO  [main:X509Util@79] - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
zookeeper_1  | 2019-07-26 15:00:13,649 [myid:1] - INFO  [main:Login@302] - Server successfully logged in.
zookeeper_1  | 2019-07-26 15:00:13,652 [myid:1] - INFO  [main:NIOServerCnxnFactory@673] - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 8 worker threads, and 64 kB direct buffers.
zookeeper_1  | 2019-07-26 15:00:13,654 [myid:1] - INFO  [main:NIOServerCnxnFactory@686] - binding to port 0.0.0.0/0.0.0.0:2181
zookeeper_1  | 2019-07-26 15:00:13,666 [myid:1] - INFO  [main:ZKDatabase@117] - zookeeper.snapshotSizeFactor = 0.33
zookeeper_1  | 2019-07-26 15:00:13,668 [myid:1] - INFO  [main:FileSnap@83] - Reading snapshot /opt/bitnami/zookeeper/data/version-2/snapshot.0
zookeeper_1  | 2019-07-26 15:00:13,689 [myid:1] - INFO  [main:FileTxnSnapLog@372] - Snapshotting: 0xb8 to /opt/bitnami/zookeeper/data/version-2/snapshot.b8
zookeeper_1  | 2019-07-26 15:00:13,706 [myid:1] - INFO  [main:ContainerManager@64] - Using checkIntervalMs=60000 maxPerMinute=10000
zookeeper_1  | 2019-07-26 15:00:13,957 [myid:1] - INFO  [SyncThread:0:FileTxnLog@216] - Creating new log file: log.b9
```

**Comment by cwienands1** [comment]
I also spent some time examining the "insides" of the Zookeeper container.

Content of /opt/bitnami/zookeeper/conf/java.env, looks OK to me.
```
$ cat java.env
export JVMFLAGS=" -Xmx1024m -Xms1024m -Djava.security.auth.login.config=/opt/bitnami/zookeeper/conf/zoo_jaas.conf"
```

Content of /opt/bitnami/zookeeper/conf/zoo_jaas.conf looks OK to me from what I can tell.
```
$ cat zoo_jaas.conf
Client {
   org.apache.zookeeper.server.auth.DigestLoginModule required
   username="client"
   password="client_password";
};
Server {
   org.apache.zookeeper.server.auth.DigestLoginModule required
      user_kafka="kafka_password";
};
```

Content of /opt/bitnami/zookeeper/conf/zoo.cfg, does NOT look OK:
```
# The number of milliseconds of each tick
tickTime=2000
# The number of ticks that the initial
# synchronization phase can take
initLimit=10
# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit=5
# the directory where the snapshot is stored.
# do not use /tmp for storage, /tmp here is just
# example sakes.
dataDir=/opt/bitnami/zookeeper/data
# the port at which the clients will connect
clientPort=2181
# the maximum number of client connections.
# increase this if you need to handle more clients
maxClientCnxns=60
#
# Be sure to read the maintenance section of the
# administrator guide before turning on autopurge.
#
# http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
#
# The number of snapshots to retain in dataDir
#autopurge.snapRetainCount=3
# Purge task interval in hours
# Set to "0" to disable auto purge feature
#autopurge.purgeInterval=1
authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
requireClientAuthScheme=sasl
```

According to this [Confluence Wiki page](https://cwiki.apache.org/confluence/display/ZOOKEEPER/Server-Server+mutual+authentication), a number of _quorum_ entries are required in the zoo.cfg file, like
```
quorum.auth.enableSasl=true
quorum.auth.learnerRequireSasl=true
quorum.auth.serverRequireSasl=true
quorum.auth.learner.loginContext=QuorumLearner
quorum.auth.server.loginContext=QuorumServer
quorum.auth.kerberos.servicePrincipal=servicename/_HOST
quorum.cnxn.threads.size=20
```

I studied the bitnami-docker-zookeeper source code as well as the _bitnami base functions_ and _helpers_ scripts in the base image but just cannot figure out how the environment variables passed into the Docker (Compose) build process translate into changes in config files (e.g. how the client and server passwords end up in the zoo_jaas.conf file). Black magic!

But now I'm stuck...

**Comment by miguelaeh** [comment]
Hi @cwienands1 ,
I see the problem. I can see always the following log for kafka either deploying with authentication or not :
```
kafka_1      | [2019-07-29 07:09:18,439] INFO Opening socket connection to server zookeeper/172.21.0.2:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
```

> According to this Confluence Wiki page, a number of quorum entries are required in the zoo.cfg file

Could you confirm if using that configuration solves the problem?

**Comment by cwienands1** [comment]
I wanted to do that but couldn't identify an installed text editor in the Docker image. I tried to install one but there is some kind of issue with _sudo_. It can't identify the logged-in user. I didn't have the time yet to pull the bitnami-docker-zookeeper source code and try build the image myself, and possibly modify the Dockerfile to install an editor during the build process (might still need to be run as the non-working sudo to access the respective config file).

**Comment by miguelaeh** [comment]
Hi @cwienands1 ,
It is not an error, that image is a non root container so you cannot execute commands as root.
Let me create an internal task to investigate it.
Thank you very much for reporting the issue. We will update this thread when we have more information.

**Comment by miguelaeh** [comment]
Hi @javieryanez ,
Thank you very much to point us to that, unfortunately we had not the time to investigate this issue yet.

**Comment by guiramos** [comment]
Any news regarding on this. It has been more than a year!!!

**Comment by miguelaeh** [comment]
Hi,
I am afraid we have not checked this issue specifically yet, we have a really small team. But we have been improving the Kafka configuration for SASL authentication mechanisms.
Using the following docker-compose and checking the logs it seems that the SASL is properly configured.
Could you give a try to this docker-compose.yml and tell us if that is what you expect:
```
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
  zookeeper2:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper2_data:/bitnami
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
  zookeeper3:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper3_data:/bitnami
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
volumes:
  zookeeper_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local
```
