### ISSUE TITLE
dynamic reconfigure didn't work

### ISSUE THREAD

**Issue by rodrigongarcia** [bitnami/bitnami-docker-zookeeper#34]
When you want to have the dynamic configuration enabled, the quorum is never reached..
This is because inside the zpath /zookeeper/config there is something like this:
```
server.1=0.0.0.0:2888:3888:participant;0.0.0.0:2181
server.2=zookeeper2:2888:3888:participant;0.0.0.0:2181
server.3=rc-zookeeper3:2888:3888:participant;0.0.0.0:2181
version=0
```

**Steps to reproduce the issue:**

1. start ensamble whit 3 nodes and the prop ZOO_RECONFIG_ENABLED=yes
i get this on logs:
```
zookeeper                | 2020-06-02 15:31:39,989 [myid:3] - ERROR [QuorumPeerListener:QuorumCnxManager$Listener@981] - As I'm leaving the listener thread, I won't be able to participate in leader election any longer: 10.70.161.213:3888
```
i try some properties to solve:
`- JVMFLAGS=-Dzookeeper.skipACL=yes -Dzookeeper.electionPortBindRetry=5 -Dzookeeper.multiAddress.enabled=true -Dzookeeper.multiAddress.reachabilityCheckEnabled=false
`

when i disabled dynamic setup it worked again.
I think it has to do with the new way of defining the server configuration, currently the image uses the old way.
https://zookeeper.apache.org/doc/r3.6.0/zookeeperReconfig.html

**Version**

- Output of `docker version`:

```Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:45 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 106
 Running: 1
 Paused: 0
 Stopped: 105
Images: 479
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 584
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-101-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55GiB
Name: PMITN009870
ID: 7HDH:YAD2:3B3H:4UFV:NEWI:SXIM:TBRN:KQ3W:L4TU:BQUY:SYVR:RMAD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mysery
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by andresbono** [comment]
Hi @rodrigongarcia, thanks for opening this issue.

Could you please share the specific docker-compose that you are using? That would help us to reproduce the problem.

Did any of the properties solve the issue? Other than disabling dynamic setup.

> i try some properties to solve:
> `- JVMFLAGS=-Dzookeeper.skipACL=yes -Dzookeeper.electionPortBindRetry=5 -Dzookeeper.multiAddress.enabled=true -Dzookeeper.multiAddress.reachabilityCheckEnabled=false `
> 
> when i disabled dynamic setup it worked again.

**Comment by rodrigongarcia** [comment]
Hi, thx for reply.
i have 3 servers each whit same docker-compose.yml (i change ZOO_SERVER_ID and ZOO_SERVERS with env vars)
```
version: '3.6'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    container_name: zookeeper
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
      - '9095:9095'
      - '8888:8080'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888
      - ZOO_4LW_COMMANDS_WHITELIST="srvr, mntr, stat, ruok, conf, isro"
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9095
      - ZOO_RECONFIG_ENABLED=yes
      - ZOO_STANDALONE_ENABLED=no
      - JVMFLAGS=-Dzookeeper.skipACL=yes -Dzookeeper.electionPortBindRetry=10 -Dzookeeper.multiAddress.enabled=true -Dzookeeper.multiAddress.reachabilityCheckEnabled=false
    networks:
      - zookeeper_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  zookeeper_network:
    driver: bridge
```

I added the settings: JVMFLAGS, only for migration from zk 3.4.9 to 3.6.1, recommended according to the zk documentation, that not solving the problem. It should be noted that I am doing is a rolling update. the first node can get quorum, but when I try to update the second it fails.

JVMFLAGS does not resolve the issue, when I change ZOO_RECONFIG_ENABLED = no, I was able to raise node 2.

maybe the problem is not the image itself, maybe the zookeeper has this problem with the dynamic configuration.

regards.
