### ISSUE TITLE
Configure server id with jumps.

### ISSUE THREAD

**Issue by rodrigongarcia** [bitnami/bitnami-docker-zookeeper#35]
i have one problem when o have active ensamble with this config:
```
server.1=zookeeper-00:2888:3888;2181
server.4=zookeeper-03:2888:3888;2181
server.7=zookeeper-06:2888:3888;2181
```
and i try migrate from non-docker to docker solution.

on this line:
https://github.com/bitnami/bitnami-docker-zookeeper/blob/baece1e26ec27a6fe8d31e67ccefb7c95d2daaeb/3/debian-10/rootfs/opt/bitnami/scripts/libzookeeper.sh#L251

Cannot set server identification, I should be able to define, for example:
```
ZOO_SERVER_ID=4
ZOO_SERVERS=1:zookeeper-00:2888:3888,4:0.0.0.0:2888:3888,7:zookeeper-06:2888:3888
```
This example is from server zookeeper-03.

regards

**Comment by jotamartos** [comment]
Hi @rodrigongarcia,

I'm sorry but I don't fully understand what's the issue here. 

>and i try migrate from non-docker to docker solution.

I understand you have a non-docker solution and want to migrate it to our [Zookeeper cluser docker solution](https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/docker-compose-cluster.yml), is this correct? Can you share the exact docker-compose.yml file you are using to deploy the solution? 

>Cannot set server identification, I should be able to define, for example:

Can you also elaborate? You can specify the ZOO_SERVERS env variable in the docker-compose and it should edit the configuration of the server. Did you do that? The docker-compose.yml file I posted above has an example about how to configure that parameter. 

Thanks

**Comment by jotamartos** [comment]
Ok @rodrigongarcia ,

I think I now know what's happening, you are trying to use non-consecutive server IDs and that's not working, right? For example, I created this docker-compose file 

```
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888
  zookeeper4:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper4_data:/bitnami
    environment:
      - ZOO_SERVER_ID=4
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888
  zookeeper7:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper7_data:/bitnami
    environment:
      - ZOO_SERVER_ID=7
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888

volumes:
  zookeeper_data:
    driver: local
  zookeeper4_data:
    driver: local
  zookeeper7_data:
    driver: local
```

and obtained errors like this one 

```
zookeeper_1   | 2020-06-04 15:13:28,605 [myid:1] - WARN  [QuorumConnectionThread-[myid=1]-5:QuorumCnxManager@400] - Cannot open channel to 2 at election address zookeeper4/172.22.0.4:3888
zookeeper_1   | java.net.NoRouteToHostException: No route to host (Host unreachable)
zookeeper_1   |         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
zookeeper_1   |         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
zookeeper_1   |         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
zookeeper_1   |         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
zookeeper_1   |         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
zookeeper_1   |         at java.base/java.net.Socket.connect(Socket.java:609)
zookeeper_1   |         at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:383)
zookeeper_1   |         at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:457)
zookeeper_1   |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
zookeeper_1   |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
zookeeper_1   |         at java.base/java.lang.Thread.run(Thread.java:834)
```

Is that what you are getting? 

Thanks

**Comment by rodrigongarcia** [comment]
yes i getting similar, you need set the network:
```
version: '3.6'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888
    networks:
      - zookeeper_network
    
  zookeeper4:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper4_data:/bitnami
    environment:
      - ZOO_SERVER_ID=4
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888
    networks:
      - zookeeper_network

  zookeeper7:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181'
    volumes:
      - zookeeper7_data:/bitnami
    environment:
      - ZOO_SERVER_ID=7
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper4:2888:3888,zookeeper7:2888:3888
    networks:
      - zookeeper_network

networks:
  zookeeper_network:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  zookeeper4_data:
    driver: local
  zookeeper7_data:
    driver: local
```
and get this error:
```
zookeeper7_1  | 2020-06-04 17:55:59,856 [myid:7] - ERROR [main:QuorumPeerMain@113] - Unexpected exception, exiting abnormally
zookeeper7_1  | java.lang.RuntimeException: My id 7 not in the peer list
zookeeper7_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:1073)
zookeeper7_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:227)
zookeeper7_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
zookeeper7_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
zookeeper7_1  | 2020-06-04 17:55:59,859 [myid:7] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
zookeeper7_1  | 2020-06-04 17:55:59,861 [myid:7] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
----
zookeeper4_1  | 2020-06-04 17:55:56,792 [myid:4] - ERROR [main:QuorumPeerMain@113] - Unexpected exception, exiting abnormally
zookeeper4_1  | java.lang.RuntimeException: My id 4 not in the peer list
zookeeper4_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:1073)
zookeeper4_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:227)
zookeeper4_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
zookeeper4_1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
zookeeper4_1  | 2020-06-04 17:55:56,799 [myid:4] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
zookeeper4_1  | 2020-06-04 17:55:56,801 [myid:4] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1

```
