### ISSUE TITLE
README.md clarification related to Docker Compose ensemble setup

### ISSUE THREAD

**Issue by vladul23** [bitnami/bitnami-docker-zookeeper#42]
README.md contains incomplete & misleading information related to Docker Compose ensemble setup

The setup has to clearly indicate that each zookeeper instance needs to be mapped to different volume.
This will bring documentation in sync with https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/docker-compose-cluster.yml

Possible fix proposed below in **bold**
zookeeper1:
 volumes:
      - /path/to/zookeeper-persistence**1**:/bitnami/zookeeper
zookeeper2:
volumes:
      - /path/to/zookeeper-persistence**2**:/bitnami/zookeeper
zookeeper3:
volumes:
      - /path/to/zookeeper-persistence**3**:/bitnami/zookeeper

**Comment by miguelaeh** [comment]
Hi,
I think the docker-compose-cluster is correct. Doing what you are proposing will not work since you are mounting the same local volume to all the containers but indifferent paths inside each container.
I think you wanted to mount different local volumes but the path inside the container should be the same in all of them.

**Comment by vladul23** [comment]
I belive both solutions work, each zookeeper using a different volume or the same volume and different folders

**Comment by miguelaeh** [comment]
That will not use a different folder, the content of the volume will be the same, but in each container, it will be mounted at diferent paths.

**Comment by vladul23** [comment]
Ok, changed my suggestion

**Comment by rafariossaa** [comment]
Hi,
  I think what you suggest is what is currently in the `docker-compose-cluster.yml`:
```
...

services:
  zookeeper:
...
    volumes:
      - zookeeper_data:/bitnami
    environment:
...


  zookeeper2:
...
    volumes:
      - zookeeper2_data:/bitnami
...


  zookeeper3:
...
    volumes:
      - zookeeper3_data:/bitnami
...


volumes:
  zookeeper_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local
```

  I think it is clear that there are 3 different volumes each one mounted in one of the containers.

  As a side node, please do not edit you previous comments to change the proposed, it renders the rest of the comments confusing. It is ok if you edit them to fix typos and formatting.
