### ISSUE TITLE
Zookeeper watcher tries to connect on 2181 despite changing the ZOO_PORT_NUMBER value

### ISSUE THREAD

**Issue by ParikhKadam** [bitnami/bitnami-docker-zookeeper#59]
**Description**

One of the zookeeper client, maybe zookeeper watcher, tries to connect on `localhost:2181` even after changing the value of `ZOO_PORT_NUMBER`.

**Steps to reproduce the issue:**

docker-compse.yml
```
version: "3.4"
services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT_NUMBER=12181
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=zookeeper1
      - ZOO_CLIENT_PASSWORD=zookeeper1
      - ZOO_SERVER_USERS=zookeeper1,admin
      - ZOO_SERVER_PASSWORDS=zookeeper1,admin
      # - ZOO_SERVERS=server.1=0.0.0.0:12888:13888
    ports:
      - "12181:12181"
    volumes:
    - ./kafka-secrets/:/bitnami/kafka/config/certs/
  kafka1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper1
    ports:
      - "19092:19092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:12181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:19093,CLIENT://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:19093,CLIENT://127.0.0.1:19092
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-512
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin
      - KAFKA_CLIENT_USER=user
      - KAFKA_CLIENT_PASSWORD=password
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=admin
      - KAFKA_ZOOKEEPER_PASSWORD=admin
      - KAFKA_CERTIFICATE_PASSWORD=top_secret
    volumes:
      - ./kafka-secrets/:/bitnami/kafka/config/certs/
```

**Describe the results you received:**

Error logs:
```
zookeeper1_1  | 2021-09-03 11:18:43,269 [myid:] - INFO  [main:ZooKeeper@637] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@51b7e5df
zookeeper1_1  | 2021-09-03 11:18:43,274 [myid:] - INFO  [main:X509Util@77] - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
zookeeper1_1  | 2021-09-03 11:18:43,280 [myid:] - INFO  [main:ClientCnxnSocket@239] - jute.maxbuffer value is 1048575 Bytes
zookeeper1_1  | 2021-09-03 11:18:43,289 [myid:] - INFO  [main:ClientCnxn@1726] - zookeeper.request.timeout value is 0. feature enabled=false
zookeeper1_1  | 2021-09-03 11:18:43,410 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):Login@317] - Client successfully logged in.
zookeeper1_1  | 2021-09-03 11:18:43,414 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):SecurityUtils@70] - Client will use DIGEST-MD5 as SASL mechanism.
zookeeper1_1  | 2021-09-03 11:18:43,510 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1171] - Opening socket connection to server localhost/127.0.0.1:2181.
zookeeper1_1  | 2021-09-03 11:18:43,513 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1173] - SASL config status: Will attempt to SASL-authenticate using Login Context section 'Client'
zookeeper1_1  | 2021-09-03 11:18:43,527 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1290] - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
zookeeper1_1  | java.net.ConnectException: Connection refused
zookeeper1_1  |         at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
zookeeper1_1  |         at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
zookeeper1_1  |         at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
zookeeper1_1  |         at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
zookeeper1_1  | KeeperErrorCode = ConnectionLoss for /
zookeeper1_1  | 2021-09-03 11:18:43,641 [myid:] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
```

**Describe the results you expected:**

Expected to start without any issues.

**Additional information you deem important (e.g. issue happens only occasionally):**

There might be some misconfigurations in kafka SASL_SSL. But I do not think that's an issue as the logs clearly mention that some client is trying to connect on 2181. 

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 18
  Running: 0
  Paused: 0
  Stopped: 18
 Images: 467
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-27-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
 Name: fxpc
 ID: E2TM:O4X3:SHKS:Z6Y2:QVRK:XGCB:X6DB:YR7C:6XC6:TAVA:TPFO:VD3Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical system running docker compose on Ubuntu 20.04.

**Comment by ParikhKadam** [comment]
Updated docker compose that does not require certificates.

```
version: "3.4"
services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT_NUMBER=12181
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=zookeeper1
      - ZOO_CLIENT_PASSWORD=zookeeper1
      - ZOO_SERVER_USERS=zookeeper1,admin
      - ZOO_SERVER_PASSWORDS=zookeeper1,admin
      - ZOO_LOG_LEVEL=all
    ports:
      - "12181:12181"
    volumes:
    - ./kafka-secrets/:/bitnami/kafka/config/certs/
  kafka1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper1
    ports:
      - "19092:19092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:12181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=admin
      - KAFKA_ZOOKEEPER_PASSWORD=admin
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
```
