### ISSUE TITLE
ZOO_LOG_LEVEL set as debug is not working as expected

### ISSUE THREAD

**Issue by arushi315** [bitnami/bitnami-docker-zookeeper#68]
Hi team,
I am observing a behavior for when I set ZOO_LOG_LEVEL=DEBUG I do not see any logs at debug level for Zookeeper service (deployed as nomad job).
Log level change to WARN, ERROR and INFO works as expected in the sense that I see log statements at these levels. 
Is there any known issue around this? I would expect some logs at debug level. There is nothing specific that I am looking for in the logs, I am just verifying the log level change behavior.
I did verify that `zookeeper.console.threshold` gets updated in `opt/bitnami/zookeeper/conf/log4j.properties` for every log level. 

Second query:  When I change the log level I restart the zookeeper service to apply the change. Is dynamic configuration supported for log level?
Does ZOO_RECONFIG_ENABLED have any play in this?

Zookeeper version: 3.6.2

Please let me know if there is any configuration required to look into this.

**Comment by migruiz4** [comment]
Hi @arushi315,

Although `ZOO_LOG_LEVEL=DEBUG` is setting `zookeeper.console.threshold=DEBUG`, the `zookeeper.root.logger` won't generate any debug log since it is configured as `INFO, CONSOLE`.

As a workaround to this issue, the variable `ZOO_LOG4J_PROP` can be used to override the log4j root logger using `DEBUG,CONSOLE`.

Tested it myself using the following docker-compose:
```

version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.6
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LOG_LEVEL=DEBUG
      - ZOO_LOG4J_PROP=DEBUG,CONSOLE

volumes:
  zookeeper_data:
    driver: local
```

For more information, I would recommend having a look at: https://stackoverflow.com/questions/26612908/why-does-zookeeper-not-use-my-log4j-properties-file-log-directory.

Regarding your second question, it would be more appropriate to ask the upstream maintainers, but I think `reconfigEnabled` may not affect logging settings since it would require reloading log4j.
