### ISSUE TITLE
Single host but multiple zookeeper containers 

### ISSUE THREAD

**Issue by NC-RKM** [bitnami/bitnami-docker-zookeeper#77]
### Name and Version

bitnami/zookeeper:3.7.0

### What is the problem this feature will solve?

Setting up a cluster on a single host and binding the Zookeeper client port to the host is not possible as the ZOO_PORT_NUMBER is used to set the client port for all the Zookeeper servers (server.X) configured in the zoo.cfg, so each cluster node would report a different client port.   

Link to code line that sets server.X config:
https://github.com/bitnami/bitnami-docker-zookeeper/blob/a1b7776b9d1f2ae3660b3d235c83c462c3dc8cfb/3.8/debian-10/rootfs/opt/bitnami/scripts/libzookeeper.sh#L193

docker compose file to reproduce 
```
version: '2'
services:
  zookeeper1:
    image: quay.io/bitnami/zookeeper:3.7.0
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_PORT_NUMBER=2181
      - ZOO_SERVERS=zookeeper1:3888:3988::1,zookeeper2:3889:3989::2,zookeeper3:3890:3990::3
      - ZOO_ENABLE_AUTH=no
      - ZOO_RECONFIG_ENABLED=false
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper2:
    image: quay.io/bitnami/zookeeper:3.7.0
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_PORT_NUMBER=2182
      - ZOO_SERVERS=zookeeper1:3888:3988::1,zookeeper2:3889:3989::2,zookeeper3:3890:3990::3
      - ZOO_ENABLE_AUTH=no
      - ZOO_RECONFIG_ENABLED=false
      - ALLOW_ANONYMOUS_LOGIN=yes
  zookeeper3:
    image: quay.io/bitnami/zookeeper:3.7.0
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_PORT_NUMBER=2183
      - ZOO_SERVERS=zookeeper1:3888:3988::1,zookeeper2:3889:3989::2,zookeeper3:3890:3990::3
      - ZOO_ENABLE_AUTH=no
      - ZOO_RECONFIG_ENABLED=false
      - ALLOW_ANONYMOUS_LOGIN=yes
```
zookeeper1 would produce a config like this where the client port should be the same for all the servers, where it should be different. 

```
server.1=zookeeper1:3888:3988;2181
server.2=zookeeper2:3889:3989;2181
server.3=zookeeper3:3890:3990;2181
```
### What is the feature you are proposing to solve the problem?

clientPort is also deprecated so the ENV ZOO_PORT_NUMBER could be removed and that part of the config moved to the ENV ZOO_SERVERS, I was looking into a pull request for it but was unsure how to support backwards compatibility as the ZOO_SERVERS is setup to allow semi-colon separation between server configs, so a one to one import would break  backwards compatibility, and choosing an other separator would make it a mess in the libzookeeper.sh file when the config is created, so i would like some input for a good way to fix this problem. 

Zookeeper doc describing that clientPort is deprecated 
https://zookeeper.apache.org/doc/r3.6.3/zookeeperReconfig.html#sc_reconfig_clientport

File the needs to be updated 
https://github.com/bitnami/bitnami-docker-zookeeper/blob/a1b7776b9d1f2ae3660b3d235c83c462c3dc8cfb/3.8/debian-10/rootfs/opt/bitnami/scripts/libzookeeper.sh#L193
