### ISSUE TITLE
Unable to create ACL rule

### ISSUE THREAD

**Issue by dfd-bluetel** [bitnami/bitnami-docker-zookeeper#8]
**Description**

Setting the password and user the service can't start up. When it tries to create ACL rule, it returns an error message saying couldn't create ACL rule. Sounds like a timeout issue, because when I try to start the service again it runs fine with ACL.

No matter if local docker-compose or and AWS docker stack.

**Steps to reproduce the issue:**

1. set the env vars ZOO_ENABLE_AUTH=yes, ZOO_SERVER_USERS and ZOO_SERVER_PASSWORDS
2. start the docker container for the very first time
3. after it returns with fail, run the container again

**Describe the results you received:**

Error message and exit code non-zero

**Describe the results you expected:**

no error message and no exiting of zookeeper service

**Version**

- Output of `docker version`: 

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 54
 Running: 6
 Paused: 0
 Stopped: 48
Images: 481
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.54GiB
Name: dfd-MacBookPro
ID: EAFM:JXDH:OXQX:ZH5P:XJS3:PBRJ:YK3N:7GVB:ISKN:FEMT:7SBX:ZD62
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.5.0
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @dfd-bluetel 

I was unable to reproduce the issue using the **docker-compose.yaml** below:

```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka,zkcli
      - ZOO_SERVER_PASSWORDS=bitnami,bitnami
      - ZOO_CLIENT_USER=zkcli
      - ZOO_CLIENT_PASSWORD=bitnami
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
volumes:
  zookeeper_data:
    driver: local
```

Could you please give it a try?

**Comment by dfd-bluetel** [comment]
My apoligies, I've forget to include my compose file:

```
version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.4.12
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=89jQ7T2cvR7a
      - ZOO_SERVER_PASSWORDS=G6cPvQEzjlraTfKqnyJ2bSGXSn83iks5NIscoOntIKLC2muiue
      - ZOO_HEAP_SIZE=1024
    ports:
      - "2181:2181"
```

Notice I used version 3.4.12 the latest stable version, I never use latest. The passwords are randomly generated though.
