### ISSUE TITLE
zoo.cfg incorrectly configured when using quorum tls

### ISSUE THREAD

**Issue by lconnell** [bitnami/bitnami-docker-zookeeper#83]
### Name and Version

bitnami/zookeeper:3.7.1-debian-10-r18 

### What steps will reproduce the bug?

```yaml
version: "3"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "3181:3181"
      - "2888:3888"
      - "9381:9381"
    hostname: zoo1
    volumes:
      - "/app/zookeeper/data:/bitnami/zookeeper"
      - "/opt/prometheus/bin/jmx_prometheus_javaagent-0.3.1.jar:/jmx_prometheus_javaagent-0.3.1.jar:ro"
      - "/opt/prometheus/bin/zookeeper_exporter.yml:/zookeeper_exporter.yml:ro"
      - "/app/kafka/ssl/keystore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks:ro"
      - "/app/kafka/ssl/truststore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks:ro"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kiosk
      - ZOO_SERVER_PASSWORDS=sasl1234
      - ZOO_CLIENT_USER=kiosk
      - ZOO_CLIENT_PASSWORD=sasl1234
      - ZOO_TLS_CLIENT_ENABLE=yes
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=jks1234
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=jks1234
      - ZOO_TLS_QUORUM_ENABLE=true
      - ZOO_TLS_PORT_NUMBER=3181
      - ZOO_TLS_QUORUM_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
      - ZOO_TLS_QUORUM_KEYSTORE_PASSWORD=jks1234
      - ZOO_TLS_QUORUM_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
      - ZOO_TLS_QUORUM_TRUSTSTORE_PASSWORD=jks1234
      - ZOO_SERVER_ID=111
      - ZOO_SERVERS=zoo1:2888:3888::111,zoo2:2888:3888::112
      - SERVER_JVMFLAGS=-javaagent:/jmx_prometheus_javaagent-0.3.1.jar=9381:/zookeeper_exporter.yml
    network_mode: host
```

### What is the expected behavior?

zoo.cfg should define servers with secure client port 3181

### What do you see instead?

```
# The number of milliseconds of each tick
tickTime=2000
# The number of ticks that the initial
# synchronization phase can take
initLimit=10
# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit=5
# the directory where the snapshot is stored.
# do not use /tmp for storage, /tmp here is just
# example sakes.
dataDir=/bitnami/zookeeper/data
# the port at which the clients will connect
clientPort=2181
# the maximum number of client connections.
# increase this if you need to handle more clients
maxClientCnxns=60
#
# Be sure to read the maintenance section of the
# administrator guide before turning on autopurge.
#
# http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
#
# The number of snapshots to retain in dataDir
autopurge.snapRetainCount=3
# Purge task interval in hours
# Set to "0" to disable auto purge feature
autopurge.purgeInterval=0

## Metrics Providers
#
# https://prometheus.io Metrics Exporter
#metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
#metricsProvider.httpPort=7000
#metricsProvider.exportJvmInfo=true
maxCnxns=0
reconfigEnabled=false
quorumListenOnAllIPs=false
4lw.commands.whitelist=srvr, mntr
maxSessionTimeout=40000
server.111=zoo1:2888:3888;2181
server.112=zoo2:2888:3888;2181
client.secure=true
ssl.clientAuth=need
secureClientPort=3181
serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
ssl.keyStore.password=jks1234
ssl.keyStore.location=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
ssl.trustStore.password=jks1234
ssl.trustStore.location=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
sslQuorum=true
ssl.quorum.clientAuth=need
ssl.quorum.keyStore.location=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
ssl.quorum.keyStore.password=jks1234
ssl.quorum.trustStore.location=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
ssl.quorum.trustStore.password=jks1234
authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
requireClientAuthScheme=sasl
```

### Additional information

Because of this, I believe I am receiving the following error?

```
zookeeper    | 2022-06-01 21:03:52,047 [myid:111] - INFO  [main:QuorumPeer@2524] - QuorumPeer communication is not secured! (SASL auth disabled)

```
